// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/tensorboard/graph_explorer/proto/graph_explorer.proto

#ifndef PROTOBUF_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto__INCLUDED
#define PROTOBUF_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/map.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace graph_explorer {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();
void protobuf_InitDefaults_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();
void protobuf_AssignDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();
void protobuf_ShutdownFile_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();

class Edge;
class Graph;
class Node;

// ===================================================================

class Node : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:graph_explorer.Node) */ {
 public:
  Node();
  virtual ~Node();

  Node(const Node& from);

  inline Node& operator=(const Node& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Node& default_instance();

  static const Node* internal_default_instance();

  void Swap(Node* other);

  // implements Message ----------------------------------------------

  inline Node* New() const { return New(NULL); }

  Node* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Node& from);
  void MergeFrom(const Node& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Node* other);
  void UnsafeMergeFrom(const Node& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // map<string, string> node_attr = 2;
  int node_attr_size() const;
  void clear_node_attr();
  static const int kNodeAttrFieldNumber = 2;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      node_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_node_attr();

  // map<string, string> metanode_attr = 3;
  int metanode_attr_size() const;
  void clear_metanode_attr();
  static const int kMetanodeAttrFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      metanode_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_metanode_attr();

  // @@protoc_insertion_point(class_scope:graph_explorer.Node)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Node_NodeAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > node_attr_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Node_MetanodeAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > metanode_attr_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Node> Node_default_instance_;

// -------------------------------------------------------------------

class Edge : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:graph_explorer.Edge) */ {
 public:
  Edge();
  virtual ~Edge();

  Edge(const Edge& from);

  inline Edge& operator=(const Edge& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Edge& default_instance();

  static const Edge* internal_default_instance();

  void Swap(Edge* other);

  // implements Message ----------------------------------------------

  inline Edge* New() const { return New(NULL); }

  Edge* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Edge& from);
  void MergeFrom(const Edge& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Edge* other);
  void UnsafeMergeFrom(const Edge& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // optional string source = 1;
  void clear_source();
  static const int kSourceFieldNumber = 1;
  const ::std::string& source() const;
  void set_source(const ::std::string& value);
  void set_source(const char* value);
  void set_source(const char* value, size_t size);
  ::std::string* mutable_source();
  ::std::string* release_source();
  void set_allocated_source(::std::string* source);

  // optional string target = 2;
  void clear_target();
  static const int kTargetFieldNumber = 2;
  const ::std::string& target() const;
  void set_target(const ::std::string& value);
  void set_target(const char* value);
  void set_target(const char* value, size_t size);
  ::std::string* mutable_target();
  ::std::string* release_target();
  void set_allocated_target(::std::string* target);

  // map<string, string> edge_attr = 3;
  int edge_attr_size() const;
  void clear_edge_attr();
  static const int kEdgeAttrFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      edge_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_edge_attr();

  // @@protoc_insertion_point(class_scope:graph_explorer.Edge)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Edge_EdgeAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > edge_attr_;
  ::google::protobuf::internal::ArenaStringPtr source_;
  ::google::protobuf::internal::ArenaStringPtr target_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Edge> Edge_default_instance_;

// -------------------------------------------------------------------

class Graph : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:graph_explorer.Graph) */ {
 public:
  Graph();
  virtual ~Graph();

  Graph(const Graph& from);

  inline Graph& operator=(const Graph& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Graph& default_instance();

  static const Graph* internal_default_instance();

  void Swap(Graph* other);

  // implements Message ----------------------------------------------

  inline Graph* New() const { return New(NULL); }

  Graph* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Graph& from);
  void MergeFrom(const Graph& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Graph* other);
  void UnsafeMergeFrom(const Graph& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated .graph_explorer.Node node = 1;
  int node_size() const;
  void clear_node();
  static const int kNodeFieldNumber = 1;
  const ::graph_explorer::Node& node(int index) const;
  ::graph_explorer::Node* mutable_node(int index);
  ::graph_explorer::Node* add_node();
  ::google::protobuf::RepeatedPtrField< ::graph_explorer::Node >*
      mutable_node();
  const ::google::protobuf::RepeatedPtrField< ::graph_explorer::Node >&
      node() const;

  // repeated .graph_explorer.Edge edge = 2;
  int edge_size() const;
  void clear_edge();
  static const int kEdgeFieldNumber = 2;
  const ::graph_explorer::Edge& edge(int index) const;
  ::graph_explorer::Edge* mutable_edge(int index);
  ::graph_explorer::Edge* add_edge();
  ::google::protobuf::RepeatedPtrField< ::graph_explorer::Edge >*
      mutable_edge();
  const ::google::protobuf::RepeatedPtrField< ::graph_explorer::Edge >&
      edge() const;

  // map<string, string> node_attr = 3;
  int node_attr_size() const;
  void clear_node_attr();
  static const int kNodeAttrFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      node_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_node_attr();

  // map<string, string> metanode_attr = 4;
  int metanode_attr_size() const;
  void clear_metanode_attr();
  static const int kMetanodeAttrFieldNumber = 4;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      metanode_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_metanode_attr();

  // map<string, string> edge_attr = 5;
  int edge_attr_size() const;
  void clear_edge_attr();
  static const int kEdgeAttrFieldNumber = 5;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      edge_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_edge_attr();

  // map<string, string> graph_attr = 6;
  int graph_attr_size() const;
  void clear_graph_attr();
  static const int kGraphAttrFieldNumber = 6;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      graph_attr() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_graph_attr();

  // @@protoc_insertion_point(class_scope:graph_explorer.Graph)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::graph_explorer::Node > node_;
  ::google::protobuf::RepeatedPtrField< ::graph_explorer::Edge > edge_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Graph_NodeAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > node_attr_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Graph_MetanodeAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > metanode_attr_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Graph_EdgeAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > edge_attr_;
  typedef ::google::protobuf::internal::MapEntryLite<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 >
      Graph_GraphAttrEntry;
  ::google::protobuf::internal::MapField<
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > graph_attr_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Graph> Graph_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Node

// optional string name = 1;
inline void Node::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Node::name() const {
  // @@protoc_insertion_point(field_get:graph_explorer.Node.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:graph_explorer.Node.name)
}
inline void Node::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:graph_explorer.Node.name)
}
inline void Node::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:graph_explorer.Node.name)
}
inline ::std::string* Node::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:graph_explorer.Node.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Node::release_name() {
  // @@protoc_insertion_point(field_release:graph_explorer.Node.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Node::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:graph_explorer.Node.name)
}

// map<string, string> node_attr = 2;
inline int Node::node_attr_size() const {
  return node_attr_.size();
}
inline void Node::clear_node_attr() {
  node_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Node::node_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Node.node_attr)
  return node_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Node::mutable_node_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Node.node_attr)
  return node_attr_.MutableMap();
}

// map<string, string> metanode_attr = 3;
inline int Node::metanode_attr_size() const {
  return metanode_attr_.size();
}
inline void Node::clear_metanode_attr() {
  metanode_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Node::metanode_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Node.metanode_attr)
  return metanode_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Node::mutable_metanode_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Node.metanode_attr)
  return metanode_attr_.MutableMap();
}

inline const Node* Node::internal_default_instance() {
  return &Node_default_instance_.get();
}
// -------------------------------------------------------------------

// Edge

// optional string source = 1;
inline void Edge::clear_source() {
  source_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Edge::source() const {
  // @@protoc_insertion_point(field_get:graph_explorer.Edge.source)
  return source_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Edge::set_source(const ::std::string& value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:graph_explorer.Edge.source)
}
inline void Edge::set_source(const char* value) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:graph_explorer.Edge.source)
}
inline void Edge::set_source(const char* value, size_t size) {
  
  source_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:graph_explorer.Edge.source)
}
inline ::std::string* Edge::mutable_source() {
  
  // @@protoc_insertion_point(field_mutable:graph_explorer.Edge.source)
  return source_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Edge::release_source() {
  // @@protoc_insertion_point(field_release:graph_explorer.Edge.source)
  
  return source_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Edge::set_allocated_source(::std::string* source) {
  if (source != NULL) {
    
  } else {
    
  }
  source_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), source);
  // @@protoc_insertion_point(field_set_allocated:graph_explorer.Edge.source)
}

// optional string target = 2;
inline void Edge::clear_target() {
  target_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Edge::target() const {
  // @@protoc_insertion_point(field_get:graph_explorer.Edge.target)
  return target_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Edge::set_target(const ::std::string& value) {
  
  target_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:graph_explorer.Edge.target)
}
inline void Edge::set_target(const char* value) {
  
  target_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:graph_explorer.Edge.target)
}
inline void Edge::set_target(const char* value, size_t size) {
  
  target_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:graph_explorer.Edge.target)
}
inline ::std::string* Edge::mutable_target() {
  
  // @@protoc_insertion_point(field_mutable:graph_explorer.Edge.target)
  return target_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Edge::release_target() {
  // @@protoc_insertion_point(field_release:graph_explorer.Edge.target)
  
  return target_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Edge::set_allocated_target(::std::string* target) {
  if (target != NULL) {
    
  } else {
    
  }
  target_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), target);
  // @@protoc_insertion_point(field_set_allocated:graph_explorer.Edge.target)
}

// map<string, string> edge_attr = 3;
inline int Edge::edge_attr_size() const {
  return edge_attr_.size();
}
inline void Edge::clear_edge_attr() {
  edge_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Edge::edge_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Edge.edge_attr)
  return edge_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Edge::mutable_edge_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Edge.edge_attr)
  return edge_attr_.MutableMap();
}

inline const Edge* Edge::internal_default_instance() {
  return &Edge_default_instance_.get();
}
// -------------------------------------------------------------------

// Graph

// repeated .graph_explorer.Node node = 1;
inline int Graph::node_size() const {
  return node_.size();
}
inline void Graph::clear_node() {
  node_.Clear();
}
inline const ::graph_explorer::Node& Graph::node(int index) const {
  // @@protoc_insertion_point(field_get:graph_explorer.Graph.node)
  return node_.Get(index);
}
inline ::graph_explorer::Node* Graph::mutable_node(int index) {
  // @@protoc_insertion_point(field_mutable:graph_explorer.Graph.node)
  return node_.Mutable(index);
}
inline ::graph_explorer::Node* Graph::add_node() {
  // @@protoc_insertion_point(field_add:graph_explorer.Graph.node)
  return node_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::graph_explorer::Node >*
Graph::mutable_node() {
  // @@protoc_insertion_point(field_mutable_list:graph_explorer.Graph.node)
  return &node_;
}
inline const ::google::protobuf::RepeatedPtrField< ::graph_explorer::Node >&
Graph::node() const {
  // @@protoc_insertion_point(field_list:graph_explorer.Graph.node)
  return node_;
}

// repeated .graph_explorer.Edge edge = 2;
inline int Graph::edge_size() const {
  return edge_.size();
}
inline void Graph::clear_edge() {
  edge_.Clear();
}
inline const ::graph_explorer::Edge& Graph::edge(int index) const {
  // @@protoc_insertion_point(field_get:graph_explorer.Graph.edge)
  return edge_.Get(index);
}
inline ::graph_explorer::Edge* Graph::mutable_edge(int index) {
  // @@protoc_insertion_point(field_mutable:graph_explorer.Graph.edge)
  return edge_.Mutable(index);
}
inline ::graph_explorer::Edge* Graph::add_edge() {
  // @@protoc_insertion_point(field_add:graph_explorer.Graph.edge)
  return edge_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::graph_explorer::Edge >*
Graph::mutable_edge() {
  // @@protoc_insertion_point(field_mutable_list:graph_explorer.Graph.edge)
  return &edge_;
}
inline const ::google::protobuf::RepeatedPtrField< ::graph_explorer::Edge >&
Graph::edge() const {
  // @@protoc_insertion_point(field_list:graph_explorer.Graph.edge)
  return edge_;
}

// map<string, string> node_attr = 3;
inline int Graph::node_attr_size() const {
  return node_attr_.size();
}
inline void Graph::clear_node_attr() {
  node_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Graph::node_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Graph.node_attr)
  return node_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Graph::mutable_node_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Graph.node_attr)
  return node_attr_.MutableMap();
}

// map<string, string> metanode_attr = 4;
inline int Graph::metanode_attr_size() const {
  return metanode_attr_.size();
}
inline void Graph::clear_metanode_attr() {
  metanode_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Graph::metanode_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Graph.metanode_attr)
  return metanode_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Graph::mutable_metanode_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Graph.metanode_attr)
  return metanode_attr_.MutableMap();
}

// map<string, string> edge_attr = 5;
inline int Graph::edge_attr_size() const {
  return edge_attr_.size();
}
inline void Graph::clear_edge_attr() {
  edge_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Graph::edge_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Graph.edge_attr)
  return edge_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Graph::mutable_edge_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Graph.edge_attr)
  return edge_attr_.MutableMap();
}

// map<string, string> graph_attr = 6;
inline int Graph::graph_attr_size() const {
  return graph_attr_.size();
}
inline void Graph::clear_graph_attr() {
  graph_attr_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
Graph::graph_attr() const {
  // @@protoc_insertion_point(field_map:graph_explorer.Graph.graph_attr)
  return graph_attr_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
Graph::mutable_graph_attr() {
  // @@protoc_insertion_point(field_mutable_map:graph_explorer.Graph.graph_attr)
  return graph_attr_.MutableMap();
}

inline const Graph* Graph::internal_default_instance() {
  return &Graph_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace graph_explorer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_2fcontrib_2ftensorboard_2fgraph_5fexplorer_2fproto_2fgraph_5fexplorer_2eproto__INCLUDED
